"""followers

Revision ID: 821e08694d00
Revises: 93fa004de5b7
Create Date: 2022-11-06 12:20:22.989788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821e08694d00'
down_revision = '93fa004de5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
